# netlify.toml

[build]
  publish = "Build"    # Folder containing index.html
  command = "#"        # No build command needed

[build.environment]
  NODE_VERSION = "18.17.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for Unity WebGL Brotli compression
[[headers]]
  for = "*.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.js.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.wasm.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/wasm"

[[headers]]
  for = "/*.data.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/Build/webgl.framework.js.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/javascript"

# Optional: Add cache control for better performance
[[headers]]
  for = "/Build/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"