[build]
  publish = "Build"    # Harus sama dengan nama folder yang berisi index.html
  command = "#"        # Tidak perlu command build

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.17.0"